apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"rook-operator","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"rook-operator"}},"spec":{"containers":[{"args":["operator"],"env":[{"name":"ROOK_REPO_PREFIX","value":"rook"}],"image":"rook/rook:v0.5.1","name":"rook-operator"}],"serviceAccountName":"rook-operator"}}}}
  creationTimestamp: 2018-07-25T18:50:01Z
  generation: 2
  labels:
    app: rook-operator
  name: rook-operator
  namespace: default
  resourceVersion: "344799"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/rook-operator
  uid: 895b2d4c-903b-11e8-b218-0c4de99bfb81
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rook-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-operator
    spec:
      containers:
      - args:
        - operator
        env:
        - name: ROOK_REPO_PREFIX
          value: rook
        image: rook/rook:v0.6.2
        imagePullPolicy: IfNotPresent
        name: rook-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-operator
      serviceAccountName: rook-operator
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-07-25T18:50:01Z
    lastUpdateTime: 2018-07-27T05:51:51Z
    message: ReplicaSet "rook-operator-677477b866" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-07-27T05:55:11Z
    lastUpdateTime: 2018-07-27T05:55:11Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
