#####################################################
# Secure traefik dashboard with https and basic auth
#####################################################

#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: traefik-dashboard
#spec:
#  routes:
#  - match: Host(`{YOUR-HOST-NAME}`)
#    kind: Rule
#    services:
#    - name: api@internal
#      kind: TraefikService
#    # optional: add basic auth
#    #middlewares: 
#    #- name: basic-auth
#    #- name: https-redirect
