kind: PersistentVolume
apiVersion: v1
metadata:
  name: ombi-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-volume-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: ombi
  name: ombi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ombi
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: VIRTUAL_HOST
          value: ombi.slips23.com
        - name: VIRTUAL_PORT
          value: "3579"
        image: linuxserver/ombi:80
        name: ombi
        ports:
        - containerPort: 3579
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: ombi-volume
      restartPolicy: Always
      volumes:
      - name: ombi-volume
        persistentVolumeClaim:
          claimName: ombi-volume-claim
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: ombi
  name: ombi
spec:
  type: NodePort
  ports:
  - name: "3579"
    port: 3579
    targetPort: 3579
  selector:
    io.kompose.service: ombi
