kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-pv
  labels:
    app: wordpress
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/kubernetes-storage
