---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.perkplexserver.com`)
      middlewares:
        - name: compress
      kind: Rule
      services:
        - name: grafana
          port: 3000
  tls:
    secretName: monitoring-ssl-cert
