version: '2'
services:
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /opt/config/radarr:/config
            - /opt/storage/Movies:/movies
            - /opt/Downloads/complete:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.slips23.com
            - VIRTUAL_PORT=7878
        restart: always
