---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-volume-claim
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
