
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft
  namespace: default
spec:
  entryPoints:
    - minecraft
  routes:
  - match: HostSNI(`minecraft.perkplexserver.com`)
    services:
    - name: minecraft-minecraft
      port: 25565
  tls: {}
