---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexpy-volume-claim
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: plexpy
  name: plexpy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: plexpy
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: VIRTUAL_HOST
          value: plexpy.perkplex.geekgalaxy.com
        - name: VIRTUAL_PORT
          value: "8181"
        image: linuxserver/plexpy
        name: plexpy
        ports:
        - containerPort: 8181
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: plexpy-volume
      restartPolicy: Always
      volumes:
      - name: plexpy-volume
        persistentVolumeClaim:
          claimName: plexpy-volume-claim
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: plexpy
  name: plexpy
spec:
  type: NodePort
  ports:
  - name: "8181"
    port: 8181
    targetPort: 8181
  selector:
    io.kompose.service: plexpy
