---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pihole-ssl-cert
  namespace: pihole
spec:
  secretName: pihole-ssl-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - '*.perkplexserver.com'

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.perkplexserver.com`)
      middlewares:
        - name: compress
      kind: Rule
      services:
        - name: pihole-tcp
          port: 80
  tls:
    secretName: pihole-ssl-cert
