apiVersion: v1
kind: Service
metadata:
  name: wordpress-golf-mysql
  labels:
    app: wordpress-golf
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-golf
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-golf-pv-claim
  labels:
    app: wordpress-golf
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-golf-mysql
  labels:
    app: wordpress-golf
spec:
  selector:
    matchLabels:
      app: wordpress-golf
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-golf
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-golf
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-golf-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-golf-pv
        persistentVolumeClaim:
          claimName: mysql-golf-pv-claim
