name: Docker Build and Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with: 
          fetch-depth: 1

      - name: Build and Push Docker Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: perkins/perkplex-nginx         
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: perkplex/nginx-docker/Dockerfile
