name: Nginx Docker Build and Push
on:
  release:
      types: [published]
jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Release Version
      id: get_version
      run: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Build and Push Nginx Docker Image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: sperkins/perkplex-nginx         
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.RELEASE_VERSION }}"
        workdir: /github/workspace/nginx-docker
