name: Docker Build and Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with: 
          fetch-depth: 1

      - name: Build and Push Docker Image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: ${{ secrets.DOCKER_IMAGE_NAME }}
          dockerfile: "../../nginx-docker/Dockerfile"
