name: Octant Docker Build and Push
on:
  release:
      types: [published]
jobs:
  build-octant:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Release Version
      id: get_version
      run: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Build and Push Octant Docker Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sperkins/perkplex-octant         
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.RELEASE_VERSION }}"
        workdir: /github/workspace/octant
