name: Docker Build and Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with: 
          fetch-depth: 1

      - name: Build and Push Docker Image
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
          TAG_NAME: "v0.0.1"
          LATEST: "true"
